namespace CSGOConfigManager.Core.Services;

/// <summary>
/// Generates and saves CS:GO configuration files (.cfg) from command lists.
/// </summary>
public sealed class ConfigFileService
{
    /// <summary>
    /// Generates a .cfg file with the specified commands.
    /// </summary>
    /// <param name="cfgDirectory">The directory where the .cfg file should be saved.</param>
    /// <param name="fileName">The name of the .cfg file (should end with .cfg).</param>
    /// <param name="commands">The commands to write to the file.</param>
    /// <returns>The full path to the generated file.</returns>
    /// <exception cref="ArgumentException">Thrown when parameters are invalid.</exception>
    /// <exception cref="DirectoryNotFoundException">Thrown when the directory does not exist.</exception>
    /// <exception cref="UnauthorizedAccessException">Thrown when write permission is denied.</exception>
    /// <exception cref="IOException">Thrown when the file cannot be written.</exception>
    public string GenerateConfig(string cfgDirectory, string fileName, IEnumerable<string> commands)
    {
        if (string.IsNullOrWhiteSpace(cfgDirectory))
            throw new ArgumentException("CS:GO cfg directory cannot be empty.", nameof(cfgDirectory));

        if (string.IsNullOrWhiteSpace(fileName))
            throw new ArgumentException("Config filename cannot be empty.", nameof(fileName));

        if (!Directory.Exists(cfgDirectory))
            throw new DirectoryNotFoundException($"CS:GO cfg directory does not exist: {cfgDirectory}");

        // Ensure filename ends with .cfg
        if (!fileName.EndsWith(".cfg", StringComparison.OrdinalIgnoreCase))
            fileName += ".cfg";

        var filePath = Path.Combine(cfgDirectory, fileName);
        var content = BuildConfigContent(commands);

        // Validate the path and write the file
        File.WriteAllText(filePath, content, System.Text.Encoding.UTF8);

        return filePath;
    }

    /// <summary>
    /// Builds the content for a .cfg file from a list of commands.
    /// </summary>
    private static string BuildConfigContent(IEnumerable<string> commands)
    {
        var lines = new List<string>
        {
            "// Generated by CS:GO Config Manager",
            "// " + DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"),
            ""
        };

        foreach (var command in commands)
        {
            if (!string.IsNullOrWhiteSpace(command))
            {
                lines.Add(command.Trim());
            }
        }

        return string.Join(Environment.NewLine, lines);
    }

    /// <summary>
    /// Generates the exec command for a given config filename.
    /// </summary>
    /// <param name="fileName">The config filename (with or without .cfg extension).</param>
    /// <returns>The exec command (e.g., "exec my_config").</returns>
    public static string GenerateExecCommand(string fileName)
    {
        if (string.IsNullOrWhiteSpace(fileName))
            throw new ArgumentException("Config filename cannot be empty.", nameof(fileName));

        // Remove .cfg extension if present
        var execName = fileName.EndsWith(".cfg", StringComparison.OrdinalIgnoreCase)
            ? fileName[..^4] // Remove last 4 characters (.cfg)
            : fileName;

        return $"exec {execName}";
    }
}
